baseURL = 'https://links.mintyfox.gay/'
locale = 'en-us'
title = 'Mintys Links'
theme = 'terminal'

[params]
    centerTheme = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[languages.en.params.logo]
    logoText = "~$ cat welcome.html"
            